package com.chroniclecryptogram.designsystem

/**
 * The press plates, generated by scripts/gen-woodcuts.mjs from
 * `src/woodcuts.tsx` -- do not edit.
 *
 * Keyed by the same names the web uses, so a puzzle's `silhouette` field
 * resolves identically on both surfaces. Each plate is drawn black and tinted at
 * the call site, which is what `fill="currentColor"` does on the web.
 */
data class Woodcut(val drawableRes: Int, val ink: PressInk)

enum class PressInk { LAMPBLACK, CINNABAR, PRUSSIAN, SEPIA }

val Woodcuts: Map<String, Woodcut> = mapOf(
    "GiSecretBook" to Woodcut(R.drawable.woodcut_secret_book, PressInk.SEPIA),
    "GiPoisonBottle" to Woodcut(R.drawable.woodcut_poison_bottle, PressInk.CINNABAR),
    "GiSailboat" to Woodcut(R.drawable.woodcut_sailboat, PressInk.LAMPBLACK),
    "GiWantedReward" to Woodcut(R.drawable.woodcut_wanted_reward, PressInk.CINNABAR),
    "GiCargoCrate" to Woodcut(R.drawable.woodcut_cargo_crate, PressInk.SEPIA),
    "GiRadioTower" to Woodcut(R.drawable.woodcut_radio_tower, PressInk.PRUSSIAN),
    "GiHospital" to Woodcut(R.drawable.woodcut_hospital, PressInk.SEPIA),
    "GiWineBottle" to Woodcut(R.drawable.woodcut_wine_bottle, PressInk.LAMPBLACK),
    "GiKey" to Woodcut(R.drawable.woodcut_key, PressInk.SEPIA),
    "GiLockedChest" to Woodcut(R.drawable.woodcut_locked_chest, PressInk.PRUSSIAN),
    "GiSecretDoor" to Woodcut(R.drawable.woodcut_secret_door, PressInk.PRUSSIAN),
    "GiTigerHead" to Woodcut(R.drawable.woodcut_tiger_head, PressInk.CINNABAR),
    "GiVial" to Woodcut(R.drawable.woodcut_vial, PressInk.PRUSSIAN),
    "GiLipstick" to Woodcut(R.drawable.woodcut_lipstick, PressInk.CINNABAR),
    "GiDrowning" to Woodcut(R.drawable.woodcut_drowning, PressInk.PRUSSIAN),
    "GiCigar" to Woodcut(R.drawable.woodcut_cigar, PressInk.SEPIA),
    "GiPoliceBadge" to Woodcut(R.drawable.woodcut_police_badge, PressInk.PRUSSIAN),
    "GiRevolver" to Woodcut(R.drawable.woodcut_revolver, PressInk.CINNABAR),
    "GiSpy" to Woodcut(R.drawable.woodcut_spy, PressInk.PRUSSIAN),
    "GiMedicalPack" to Woodcut(R.drawable.woodcut_medical_pack, PressInk.LAMPBLACK),
    "GiSuitcase" to Woodcut(R.drawable.woodcut_suitcase, PressInk.SEPIA),
    "GiFishingHook" to Woodcut(R.drawable.woodcut_fishing_hook, PressInk.LAMPBLACK),
    "GiPearlNecklace" to Woodcut(R.drawable.woodcut_pearl_necklace, PressInk.SEPIA),
    "GiCrossedPistols" to Woodcut(R.drawable.woodcut_crossed_pistols, PressInk.CINNABAR),
    "GiHandcuffs" to Woodcut(R.drawable.woodcut_handcuffs, PressInk.PRUSSIAN),
    "GiPrisoner" to Woodcut(R.drawable.woodcut_prisoner, PressInk.CINNABAR),
    "GiGoldBar" to Woodcut(R.drawable.woodcut_gold_bar, PressInk.SEPIA),
    "GiGavel" to Woodcut(R.drawable.woodcut_gavel, PressInk.PRUSSIAN),
    "GiScrollUnfurled" to Woodcut(R.drawable.woodcut_scroll_unfurled, PressInk.SEPIA),
    "GiSunrise" to Woodcut(R.drawable.woodcut_sunrise, PressInk.LAMPBLACK),
    "GiPocketWatch" to Woodcut(R.drawable.woodcut_pocket_watch, PressInk.SEPIA),
)
