package com.chroniclecryptogram.cipher

import com.chroniclecryptogram.cipher.model.CipherSymbol
import com.chroniclecryptogram.cipher.model.SymbolCategory

/**
 * The 54 cipher glyphs, ported from ZODIAC_SYMBOLS_PALETTE in
 * `src/utils/cipherEngine.ts`.
 *
 * Generated by scripts/gen-palette.mjs -- do not edit, and do not reorder. The
 * seeded Fisher-Yates shuffle in [CipherEngine] indexes into this list, so
 * moving one entry changes the cipher of every puzzle.
 *
 * The glyphs span Latin Extended, Canadian Aboriginal, Lisu, Hangul, Greek, APL
 * and Geometric Shapes. Android's Noto fallback does not cover all of them on
 * every device, so the UI must render them with the bundled subset font rather
 * than the system default.
 */
internal val ZodiacSymbolsPalette: List<CipherSymbol> = listOf(
    CipherSymbol("zod_A", "A", "Letter A", SymbolCategory.ZODIAC),
    CipherSymbol("zod_B", "B", "Letter B", SymbolCategory.ZODIAC),
    CipherSymbol("zod_rev_C", "Ↄ", "Reversed C", SymbolCategory.INVERTED),
    CipherSymbol("zod_D", "D", "Letter D", SymbolCategory.ZODIAC),
    CipherSymbol("zod_rev_D", "ᗡ", "Reversed D", SymbolCategory.INVERTED),
    CipherSymbol("zod_E", "E", "Letter E", SymbolCategory.ZODIAC),
    CipherSymbol("zod_rev_E", "Ǝ", "Reversed E", SymbolCategory.INVERTED),
    CipherSymbol("zod_F", "F", "Letter F", SymbolCategory.ZODIAC),
    CipherSymbol("zod_inv_F", "Ⅎ", "Turned F", SymbolCategory.INVERTED),
    CipherSymbol("zod_6", "6", "Numeral 6", SymbolCategory.ZODIAC),
    CipherSymbol("zod_H", "H", "Letter H", SymbolCategory.ZODIAC),
    CipherSymbol("zod_I", "I", "Serif I", SymbolCategory.ZODIAC),
    CipherSymbol("zod_anchor_I", "Ɪ", "Curved Serif I", SymbolCategory.ZODIAC),
    CipherSymbol("zod_J", "J", "Letter J", SymbolCategory.ZODIAC),
    CipherSymbol("zod_turn_J", "Ꞁ", "Turned J", SymbolCategory.INVERTED),
    CipherSymbol("zod_K", "K", "Letter K", SymbolCategory.ZODIAC),
    CipherSymbol("zod_rev_K", "ꓘ", "Reversed K", SymbolCategory.INVERTED),
    CipherSymbol("zod_tilt_K", "ㅈ", "Tilted K", SymbolCategory.INVERTED),
    CipherSymbol("zod_L", "L", "Letter L", SymbolCategory.ZODIAC),
    CipherSymbol("zod_rev_L", "ᒧ", "Reversed L", SymbolCategory.INVERTED),
    CipherSymbol("zod_M", "M", "Letter M", SymbolCategory.ZODIAC),
    CipherSymbol("zod_N", "N", "Letter N", SymbolCategory.ZODIAC),
    CipherSymbol("zod_O", "O", "Letter O", SymbolCategory.ZODIAC),
    CipherSymbol("zod_P", "P", "Letter P", SymbolCategory.ZODIAC),
    CipherSymbol("zod_turn_b", "q", "Turned b / q", SymbolCategory.INVERTED),
    CipherSymbol("zod_Q", "Q", "Letter Q", SymbolCategory.ZODIAC),
    CipherSymbol("zod_slash_Q", "⍉", "Slashed Q", SymbolCategory.ZODIAC),
    CipherSymbol("zod_R", "R", "Letter R", SymbolCategory.ZODIAC),
    CipherSymbol("zod_rev_R", "Я", "Reversed R", SymbolCategory.INVERTED),
    CipherSymbol("zod_S", "S", "Letter S", SymbolCategory.ZODIAC),
    CipherSymbol("zod_T", "T", "Letter T", SymbolCategory.ZODIAC),
    CipherSymbol("zod_inv_T", "⊥", "Inverted T", SymbolCategory.INVERTED),
    CipherSymbol("zod_U", "U", "Letter U", SymbolCategory.ZODIAC),
    CipherSymbol("zod_V", "V", "Letter V", SymbolCategory.ZODIAC),
    CipherSymbol("zod_inv_V", "∧", "Inverted V", SymbolCategory.INVERTED),
    CipherSymbol("zod_W", "W", "Letter W", SymbolCategory.ZODIAC),
    CipherSymbol("zod_X", "X", "Letter X", SymbolCategory.ZODIAC),
    CipherSymbol("zod_Y", "Y", "Letter Y", SymbolCategory.ZODIAC),
    CipherSymbol("zod_Z", "Z", "Letter Z", SymbolCategory.ZODIAC),
    CipherSymbol("zod_hollow_tri", "△", "Hollow Triangle", SymbolCategory.GEOMETRIC),
    CipherSymbol("zod_dot_tri", "◬", "Triangle with Dot", SymbolCategory.GEOMETRIC),
    CipherSymbol("zod_solid_tri", "▲", "Solid Triangle", SymbolCategory.GEOMETRIC),
    CipherSymbol("zod_hollow_sq", "□", "Hollow Square", SymbolCategory.GEOMETRIC),
    CipherSymbol("zod_dot_sq", "⊡", "Square with Dot", SymbolCategory.GEOMETRIC),
    CipherSymbol("zod_half_sq", "◪", "Diagonal Half Square", SymbolCategory.GEOMETRIC),
    CipherSymbol("zod_solid_sq", "■", "Solid Square", SymbolCategory.GEOMETRIC),
    CipherSymbol("zod_bullseye", "⦿", "Bullseye Circle", SymbolCategory.GEOMETRIC),
    CipherSymbol("zod_solid_circle", "●", "Solid Circle", SymbolCategory.GEOMETRIC),
    CipherSymbol("zod_horiz_circle", "⦵", "Circle with Horizontal Bar", SymbolCategory.GEOMETRIC),
    CipherSymbol("zod_vert_circle", "ϕ", "Circle with Vertical Bar", SymbolCategory.GEOMETRIC),
    CipherSymbol("zod_crosshair", "⊕", "Zodiac Crosshair", SymbolCategory.ZODIAC),
    CipherSymbol("zod_plus", "+", "Cross / Plus", SymbolCategory.GEOMETRIC),
    CipherSymbol("zod_fwd_slash", "/", "Forward Slash", SymbolCategory.GEOMETRIC),
    CipherSymbol("zod_back_slash", "\\", "Backslash", SymbolCategory.GEOMETRIC),
)
