package com.chroniclecryptogram.designsystem.theme

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

/**
 * The ink-and-paper palette, generated by scripts/gen-theme.mjs from
 * `src/styles/tokens.css` -- do not edit by hand.
 *
 * Deliberately not a Material `ColorScheme`. This is not a tonal palette and
 * roles like `surfaceContainerHigh` have no meaning here; [ChronicleTheme]
 * derives a minimal ColorScheme separately so Material's own components do not
 * look alien.
 *
 * Dark mode inherits any token it does not override, matching the CSS cascade.
 * Inherited today: inkCinnabar, inkCream.
 */
@Immutable
data class ChronicleColors(
    val inkLampblack: Color,
    val inkCinnabar: Color,
    val inkPrussian: Color,
    val inkSepia: Color,
    val ink: Color,
    val inkCream: Color,
    val brass: Color,
    val cinnabar: Color,
    val selected: Color,
    val selectedInk: Color,
    val paper: Color,
    val paperDesk: Color,
    val paperNight: Color,
    val paperDeskNight: Color,
    val paperMasthead: Color,
    val paperSheet: Color,
    val paperCard: Color,
    val paperReading: Color,
    val paperGrain: Color,
    val paperGrainFill: Color,
    val paperScanDot: Color,
    val paperScanDot2: Color,
    val paperScanFill: Color,
    val paperRule: Color,
    val scrollTrack: Color,
    val scrollTrackEdge: Color,
    /** `--ring: var(--brass)`, an alias in the CSS. */
    val ring: Color,
)

val LightChronicleColors: ChronicleColors
    get() = ChronicleColors(
        inkLampblack = Color(0xFF1C1A17),
        inkCinnabar = Color(0xFF9E2B1E),
        inkPrussian = Color(0xFF1E2E3D),
        inkSepia = Color(0xFF523B2A),
        ink = Color(0xFF1C1917),
        inkCream = Color(0xFFF7F3E8),
        brass = Color(0xFF8A7340),
        cinnabar = Color(0xFF9E2B1E),
        selected = Color(0xFFFFE8A3),
        selectedInk = Color(0xFF1C1917),
        paper = Color(0xFFFBF7EE),
        paperDesk = Color(0xFFCAC3B4),
        paperNight = Color(0xFFD6C9B0),
        paperDeskNight = Color(0xFF7C7058),
        paperMasthead = Color(0xFFEBE4D4),
        paperSheet = Color(0xFFFCF9F2),
        paperCard = Color(0xFFFDFBF6),
        paperReading = Color(0xFFFEF3C7),
        paperGrain = Color(0xB8D8CCB6),
        paperGrainFill = Color(0xFFF6F1E7),
        paperScanDot = Color(0xFFD3C7B2),
        paperScanDot2 = Color(0xFFC7BAA2),
        paperScanFill = Color(0xFFF4EEE2),
        paperRule = Color(0xFFC4B79A),
        scrollTrack = Color(0xFFE4D6B8),
        scrollTrackEdge = Color(0xFFC4B48A),
        ring = Color(0xFF8A7340),
    )

val DarkChronicleColors: ChronicleColors
    get() = ChronicleColors(
        inkLampblack = Color(0xFFF7F3E8),
        inkCinnabar = Color(0xFF9E2B1E),
        inkPrussian = Color(0xFFA8C0D0),
        inkSepia = Color(0xFFC4A07A),
        ink = Color(0xFFF7F3E8),
        inkCream = Color(0xFFF7F3E8),
        brass = Color(0xFFC4B48A),
        cinnabar = Color(0xFFE07060),
        selected = Color(0xFFFFE8A3),
        selectedInk = Color(0xFF1C1917),
        paper = Color(0xFF1C1A17),
        paperDesk = Color(0xFF141210),
        paperNight = Color(0xFF241C14),
        paperDeskNight = Color(0xFF1A1610),
        paperMasthead = Color(0xFF32281F),
        paperSheet = Color(0xFF1A1712),
        paperCard = Color(0xFF2A241C),
        paperReading = Color(0xFF3F3420),
        paperGrain = Color(0x735A4A34),
        paperGrainFill = Color(0xFF1C1A17),
        paperScanDot = Color(0xFF3A3228),
        paperScanDot2 = Color(0xFF2E2820),
        paperScanFill = Color(0xFF1C1A17),
        paperRule = Color(0xFF5A4C3A),
        scrollTrack = Color(0xFF241C14),
        scrollTrackEdge = Color(0xFF3A3228),
        ring = Color(0xFFC4B48A),
    )
