/**
 * Generates the Compose colour tokens from src/styles/tokens.css.
 *
 *   node scripts/gen-theme.mjs
 *
 * The CSS is the single source of truth for the palette. Transcribing ~30 hex
 * values twice (light and dark) by hand is exactly the kind of thing that drifts
 * silently, and a wrong dark-mode value is invisible until someone opens the app
 * at night.
 *
 * Only the `:root` and `html.theme-dark` custom properties are read. The Tailwind
 * stone-scale overrides are deliberately skipped: they exist so hard-coded
 * `text-stone-*` classes invert on the web, and Compose has no equivalent.
 */
import { readFileSync, writeFileSync } from 'node:fs';

const CSS = 'src/styles/tokens.css';
const OUT =
  'android/core/designsystem/src/main/kotlin/com/chroniclecryptogram/designsystem/theme/Color.kt';

/** Tokens Compose cannot use: CSS filters, env() insets, scrollbar hints. */
const SKIP = new Set(['plate-night', 'safe-top', 'safe-right', 'safe-bottom', 'safe-left']);

const css = readFileSync(CSS, 'utf8');

/**
 * Anchored at the start of a line and followed by `{`, because both selector
 * names also appear in the file's opening comment -- matching that instead
 * silently yields the wrong block.
 */
function block(selector) {
  const rule = new RegExp(`^\\s*${selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\s*\\{`, 'm');
  const match = rule.exec(css);
  if (!match) throw new Error(`gen-theme: no ${selector} rule in ${CSS}`);
  const open = css.indexOf('{', match.index);
  const close = css.indexOf('}', open);
  if (close < 0) throw new Error(`gen-theme: unterminated ${selector} rule in ${CSS}`);
  return css.slice(open + 1, close);
}

function tokens(selector) {
  const out = new Map();
  for (const line of block(selector).split('\n')) {
    const match = line.match(/^\s*--([a-z0-9-]+)\s*:\s*([^;]+);/i);
    if (!match) continue;
    const [, name, rawValue] = match;
    if (SKIP.has(name) || name.startsWith('color-stone-')) continue;
    const value = rawValue.trim();
    if (value.startsWith('var(')) continue; // aliases are resolved below
    const argb = toArgb(value);
    if (argb) out.set(name, argb);
  }
  return out;
}

/** #rgb, #rrggbb and rgba() -> Compose's 0xAARRGGBB. */
function toArgb(value) {
  const hex = value.match(/^#([0-9a-f]{3}|[0-9a-f]{6})$/i);
  if (hex) {
    const digits =
      hex[1].length === 3
        ? hex[1].split('').map((c) => c + c).join('')
        : hex[1];
    return `0xFF${digits.toUpperCase()}`;
  }
  const rgba = value.match(/^rgba?\(\s*([\d.]+)[,\s]+([\d.]+)[,\s]+([\d.]+)(?:[,/\s]+([\d.]+))?\s*\)$/i);
  if (rgba) {
    const [, r, g, b, a] = rgba;
    const alpha = Math.round((a === undefined ? 1 : Number(a)) * 255);
    const byte = (n) => Number(n).toString(16).padStart(2, '0').toUpperCase();
    return `0x${byte(alpha)}${byte(r)}${byte(g)}${byte(b)}`;
  }
  return null;
}

const camel = (name) => name.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());

const light = tokens(':root');
const dark = tokens('html.theme-dark');

// `--ring: var(--brass)` is an alias, and dark mode inherits anything it does not
// override -- both mirror how the cascade actually behaves in the browser.
const names = [...light.keys()];
const missingInDark = names.filter((name) => !dark.has(name));

const property = (name) => `    val ${camel(name)}: Color,`;
const value = (map, name) => `        ${camel(name)} = Color(${map.get(name) ?? light.get(name)}),`;

writeFileSync(
  OUT,
  `package com.chroniclecryptogram.designsystem.theme

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

/**
 * The ink-and-paper palette, generated by scripts/gen-theme.mjs from
 * \`src/styles/tokens.css\` -- do not edit by hand.
 *
 * Deliberately not a Material \`ColorScheme\`. This is not a tonal palette and
 * roles like \`surfaceContainerHigh\` have no meaning here; [ChronicleTheme]
 * derives a minimal ColorScheme separately so Material's own components do not
 * look alien.
 *
 * Dark mode inherits any token it does not override, matching the CSS cascade.
${missingInDark.length ? ` * Inherited today: ${missingInDark.map(camel).join(', ')}.\n` : ''} */
@Immutable
data class ChronicleColors(
${names.map(property).join('\n')}
    /** \`--ring: var(--brass)\`, an alias in the CSS. */
    val ring: Color,
)

val LightChronicleColors: ChronicleColors
    get() = ChronicleColors(
${names.map((name) => value(light, name)).join('\n')}
        ring = Color(${light.get('brass')}),
    )

val DarkChronicleColors: ChronicleColors
    get() = ChronicleColors(
${names.map((name) => value(dark, name)).join('\n')}
        ring = Color(${dark.get('brass') ?? light.get('brass')}),
    )
`
);

console.log(
  `Wrote ${OUT}\n  ${names.length} tokens; ${missingInDark.length} inherited by dark mode` +
    (missingInDark.length ? ` (${missingInDark.join(', ')})` : '')
);
