/**
 * Generates Palette.kt from the palette fixture, so the 54 glyphs are never
 * transcribed by hand. Run from the repo root:
 *
 *   node scripts/gen-palette.mjs
 *
 * The order of the list is load-bearing -- the seeded Fisher-Yates shuffle
 * indexes into it -- which is exactly why this is generated rather than typed.
 */
import { readFileSync, writeFileSync } from 'node:fs';

const FIXTURE = 'android/core/cipher/src/test/resources/fixtures/palette.json';
const OUT = 'android/core/cipher/src/main/kotlin/com/chroniclecryptogram/cipher/Palette.kt';

const kotlinString = (value) =>
  '"' +
  value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\$/g, '\\$') +
  '"';

const { symbols } = JSON.parse(readFileSync(FIXTURE, 'utf8'));

const entries = symbols
  .map(
    (symbol) =>
      `    CipherSymbol(${kotlinString(symbol.id)}, ${kotlinString(symbol.glyph)}, ` +
      `${kotlinString(symbol.name)}, SymbolCategory.${symbol.category.toUpperCase()}),`
  )
  .join('\n');

writeFileSync(
  OUT,
  `package com.chroniclecryptogram.cipher

import com.chroniclecryptogram.cipher.model.CipherSymbol
import com.chroniclecryptogram.cipher.model.SymbolCategory

/**
 * The 54 cipher glyphs, ported from ZODIAC_SYMBOLS_PALETTE in
 * \`src/utils/cipherEngine.ts\`.
 *
 * Generated by scripts/gen-palette.mjs -- do not edit, and do not reorder. The
 * seeded Fisher-Yates shuffle in [CipherEngine] indexes into this list, so
 * moving one entry changes the cipher of every puzzle.
 *
 * The glyphs span Latin Extended, Canadian Aboriginal, Lisu, Hangul, Greek, APL
 * and Geometric Shapes. Android's Noto fallback does not cover all of them on
 * every device, so the UI must render them with the bundled subset font rather
 * than the system default.
 */
internal val ZodiacSymbolsPalette: List<CipherSymbol> = listOf(
${entries}
)
`
);

console.log(`Wrote ${OUT} with ${symbols.length} symbols`);
